name: Face Emotion Recognition CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic import tests
        run: |
          python -c "import torch; import torchvision; import numpy; import pandas; import sklearn; import matplotlib; import seaborn; import onnx; import onnxruntime; import cv2"

      - name: Run dry-run of test script
        run: |
          python test_torch.py || true
        # (the script will fail if .npy data is missing, this checks for syntax/runtime errors)

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
